site_name: Laredo Documentation
site_description: Documentation, installation guide, and usage guide for Laredo.
site_dir: site
docs_dir: docs
use_directory_urls: false

theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.instant
    - search.highlight
    - search.suggest

nav:
  - Home: index.md
  - Install: installation.md
  - Usage: 
    - Quick Start: usage.md
    - Basic Creation: basic-creation-mode.md
    - Advanced Creation: advanced-creation-mode.md
  - Configuration: configuration.md
  - Local Deployment: local-deployment.md

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
plugins:
  - mkdocs-video
extra_css:
  - stylesheets/extra.css
