{{- if include "laredo.gatewayAPIEnabled" . }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gatewayAPI.gateway.name }}
  namespace: {{ .Values.backend.namespace }}
  labels:
    {{- include "laredo.labels" . | nindent 4 }}
spec:
  gatewayClassName: {{ .Values.gatewayAPI.gatewayClassName }}
  listeners:
  {{- range .Values.gatewayAPI.gateway.listeners }}
  - name: {{ .name }}
    port: {{ .port }}
    protocol: {{ .protocol }}
    allowedRoutes:
      namespaces:
        from: Same
  {{- end }}
{{- end }}
