{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: laredo-ingress
  namespace: {{ .Values.backend.namespace }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  # {{- if .Values.ingress.tls }}
  # tls:
  #   {{- toYaml .Values.ingress.tls | nindent 4 }}
  # {{- end }}
  rules:
    {{- if .Values.backend.deploy_s3_storage }}
    - host: {{ index .Values.ingress.hosts 0 "host" }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: localstack-service
                port:
                  number: {{ .Values.backend.s3_service_port }}
    {{- end }}
    {{- if .Values.backend.deploy_mlflow }}
    - host: {{ index .Values.ingress.hosts 1 "host" }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mlflow-service
                port:
                  number: {{ int .Values.backend.mlflow_tracking_uri_port }}
    {{- end }}
    - host: {{ index .Values.ingress.hosts 2 "host" }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.frontend.service.name }}
                port:
                  number: {{ .Values.frontend.service.port }}
{{- end }}