apiVersion: v1
kind: Secret
metadata:
  name: laredo-mlflow-secret
  namespace: {{ .Values.frontend.namespace}}
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.backend.s3_access_key | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.backend.s3_secret_key | b64enc }} 
  AWS_DEFAULT_REGION: {{ .Values.backend.s3_region | b64enc }} 