apiVersion: apps/v1
kind: Deployment
metadata:
  name: laredo-backend
  namespace: {{ .Values.backend.namespace}}
  labels:
    app: laredo-backend
spec:
  serviceAccountName: backend-account
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: laredo-backend
  template:
    metadata:
      labels:
        app: laredo-backend
    spec:
      serviceAccountName: backend-account
      containers:
      - name: laredo-backend
        image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
        imagePullPolicy: IfNotPresent
        env:
        - name: TRACKING_URI_IP
          value: {{ quote .Values.backend.mlflow_tracking_uri_ip }}
        - name: TRACKING_URI_PORT
          value: {{ quote .Values.backend.mlflow_tracking_uri_port }}
        {{- if and .Values.backend.AWS_ACCESS_KEY_ID .Values.backend.AWS_SECRET_ACCESS_KEY }}
        - name: S3_ENDPOINT_URL
          value: {{ quote .Values.backend.MLFLOW_S3_ENDPOINT_URL }}
        {{- if .Values.backend.deploy_s3_storage }}
        - name: S3_INTERNAL_ENDPOINT_URL
          value: {{ quote .Values.backend.S3_INTERNAL_ENDPOINT_URL }}
        {{- end }}
        - name: DATASET_BUCKET_NAME
          value: {{ quote .Values.backend.DATASET_BUCKET_NAME }}
        - name: TRAINER_IMAGE
          value: {{ .Values.backend.TRAINER_IMAGE}}
        - name: TRAINER_TAG
          value: {{ .Values.backend.TRAINER_TAG}}
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: laredo-mlflow-secret
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: laredo-mlflow-secret
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_DEFAULT_REGION
          valueFrom:
            secretKeyRef:
              name: laredo-mlflow-secret
              key: AWS_DEFAULT_REGION
        {{- end }}
        ports:
        - containerPort: {{ .Values.backend.service.port }}