apiVersion: v1
kind: Secret
metadata:
  name: laredo-mlflow-secret
  namespace: {{ .Values.frontend.namespace}}
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.backend.AWS_ACCESS_KEY_ID | b64enc  }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.backend.AWS_SECRET_ACCESS_KEY | b64enc }} 
  AWS_DEFAULT_REGION: {{ .Values.backend.AWS_DEFAULT_REGION | b64enc  }} 