apiVersion: v1
kind: Service
metadata:
  name: laredo-backend
  namespace: {{ .Values.backend.namespace}}
spec:
  selector:
    app: laredo-backend
  ports:
  - protocol: TCP
    port: {{ .Values.backend.service.port }}
    targetPort: {{ .Values.backend.service.port }}
  type: {{ .Values.backend.service.type}}
