name: Build and push Docker image for backend
on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'  # Trigger only if files in the 'backend' directory are changed
env:
  REGISTRY: ghcr.io
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Read version
        id: version
        run: echo "VERSION=$(cat backend/VERSION)" >> $GITHUB_OUTPUT

      - name: Extract metadata (tags, labels) for Docker # For backend API image
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/istr-uc/laredomlops-backend:${{ steps.version.outputs.VERSION }}
      - name: Build and push Docker image # For backend API image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: ${{ env.REGISTRY }}/istr-uc/laredomlops-backend:${{ steps.version.outputs.VERSION }}
          labels: ${{ steps.meta.outputs.labels }}
      
      - name: Extract metadata (tags, labels) for Docker # For backend trainer image
        id: meta_trainer
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/istr-uc/laredomlops-trainer:${{ steps.version.outputs.VERSION }}
      - name: Build and push Docker image # For backend trainer image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: ${{ env.REGISTRY }}/istr-uc/laredomlops-trainer:${{ steps.version.outputs.VERSION }}
          labels: ${{ steps.meta_trainer.outputs.labels }}